name: Lint

on:
  push:
    branches: "*"
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 7
      matrix:
        platform: ["ubuntu-latest"]
        tox-env: ["py39, py310", "py311", "py312", "py313"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Create virtual environment and install dependencies
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install tox tox-uv
      - name: Run tests
        run: |
          source .venv/bin/activate
          tox run -e mypy,ruff

